if(NOT DEFINED ROOT)
    message(FATAL_ERROR "ROOT was not supplied")
endif()
function(require_text file needle description)
    file(READ "${ROOT}/${file}" content)
    string(FIND "${content}" "${needle}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing ${description} in ${file}: ${needle}")
    endif()
endfunction()
function(forbid_text file needle description)
    file(READ "${ROOT}/${file}" content)
    string(FIND "${content}" "${needle}" found)
    if(NOT found EQUAL -1)
        message(FATAL_ERROR "Unexpected ${description} in ${file}: ${needle}")
    endif()
endfunction()

require_text("cmake/OmniIdentity.cmake" "set(OMNI_PRODUCT_NAME \"OmniConvertCS\")" "central product name")
require_text("cmake/OmniIdentity.cmake" "set(OMNI_VERSION \"1.06.0\")" "central application version")
require_text("CMakeLists.txt" [=[include("${CMAKE_CURRENT_LIST_DIR}/cmake/OmniIdentity.cmake")]=] "central identity include")
require_text("CMakeLists.txt" [=[project(OmniConvertCpp VERSION ${OMNI_VERSION}]=] "central project version routing")
require_text("src/gui/win32/dialog_proc.cpp" "SetWindowTextW(window, omni::identity::window_title_w.data())" "title-bar identity routing")
require_text("src/cli/cli_app.cpp" "omni::identity::window_title" "CLI identity routing")
require_text("src/cli/cli_app.cpp" "const std::string_view executable = omni::identity::executable_name" "CLI executable-name routing")
require_text("src/cli/analyze_cli.cpp" "omni::identity::executable_name" "analyze CLI executable-name routing")
require_text("src/formats/pnach/pnach_writer.cpp" "omni::identity::converted_by" "PNACH identity routing")
require_text("CMakeLists.txt" [=[OUTPUT_NAME "${OMNI_EXECUTABLE_NAME}"]=] "central executable name routing")
require_text("tools/build-windows7-x64.ps1" "cmake\\OmniIdentity.cmake" "build-script identity routing")
require_text("tools/build-windows7-x64.ps1" "Optional docs\\WINDOWS7_BUILD.md was not found; skipping it." "optional build documentation")
require_text("CMakeLists.txt" "src/gui/win32/context_controls.cpp" "context-control GUI source")
require_text("CMakeLists.txt" "src/cli/analyze_cli.cpp" "analyze CLI source")
require_text("src/gui/win32/resources/resource.rc" "IDC_EDIT_AR2_CURRENT" "current AR2 key indicator")
require_text("src/gui/win32/resources/resource.rc" "WS_CLIPCHILDREN" "resize-safe child clipping")
require_text("src/gui/win32/layout.cpp" "BeginDeferWindowPos" "batched resize layout")
require_text("src/gui/win32/layout.cpp" "SWP_NOCOPYBITS" "stale resize bitmap suppression")
require_text("src/gui/win32/layout.cpp" "RDW_INVALIDATE | RDW_ERASE | RDW_ALLCHILDREN | RDW_UPDATENOW" "complete post-layout repaint")
require_text("src/gui/win32/dialog_proc.cpp" "wparam != SIZE_MINIMIZED" "minimized resize guard")
require_text("src/gui/win32/resources/resource.rc" [[    POPUP "Options"
    BEGIN
        POPUP "Omni Options"]] "Options -> Omni Options submenu hierarchy")
require_text("src/gui/win32/resources/resource.rc" [[        END
        MENUITEM SEPARATOR
        MENUITEM "Make Organizers"]] "Make Organizers remains directly under Options")
require_text("src/gui/win32/resources/resource.rc" "MENUITEM \"CMP Output Mode\"" "CMP Output Mode menu item")
require_text("src/gui/win32/app_state.hpp" "TransposeMode::original" "Original GUI transpose default")
require_text("src/gui/win32/settings.cpp" "CmpOutputMode" "CMP output setting persistence")
require_text("src/gui/win32/conversion_controller.cpp" "request.cmp_output_mode = state->cmp_output_mode" "CMP output request routing")
require_text("src/gui/win32/resources/resource.rc" "IDC_EDIT_GAMEID_INPUT" "input ARMAX Game ID control")
require_text("src/gui/win32/resources/resource.rc" "IDC_EDIT_GAMEID_OUTPUT" "output ARMAX Game ID control")
require_text("src/gui/win32/resources/resource.rc" "MENUITEM \"Clear Input\"" "Clear Input Edit-menu command")
require_text("src/gui/win32/resources/resource.rc" "MENUITEM \"Clear Output\"" "Clear Output Edit-menu command")
require_text("src/gui/win32/resources/resource.rc" "\"A\",        ID_EDIT_SELECTALL, VIRTKEY, CONTROL" "Ctrl+A accelerator")
require_text("src/gui/win32/resources/resource.rc" "\"C\",        ID_EDIT_COPY, VIRTKEY, CONTROL" "Ctrl+C accelerator")
require_text("src/gui/win32/resources/resource.rc" "\"K\",        ID_AR2_KEY, VIRTKEY, CONTROL" "Ctrl+K accelerator")
require_text("src/gui/win32/resources/resource.rc" "\"M\",        ID_OPTIONS_ARMAX, VIRTKEY, CONTROL" "Ctrl+M accelerator")
require_text("src/gui/win32/resources/resource.rc" "\"S\",        ID_FILE_SAVEASTEXT, VIRTKEY, CONTROL" "Ctrl+S accelerator")
require_text("src/gui/win32/resources/resource.rc" "\"S\",        ID_EDIT_SWAP, VIRTKEY, CONTROL, SHIFT" "Ctrl+Shift+S accelerator")
require_text("src/gui/win32/resources/resource.rc" "\"V\",        ID_EDIT_PASTE, VIRTKEY, CONTROL" "Ctrl+V accelerator")
require_text("src/gui/win32/resources/resource.rc" "\"X\",        ID_EDIT_CUT, VIRTKEY, CONTROL" "Ctrl+X accelerator")
require_text("src/gui/win32/resources/resource.rc" "\"Z\",        ID_EDIT_UNDO, VIRTKEY, CONTROL" "Ctrl+Z accelerator")
forbid_text("src/gui/win32/resources/resource.rc" "\"^" "quoted control-character accelerator syntax")
forbid_text("src/gui/win32/resources/resource.rc" "IDC_EDIT_OUT,253,22,240,270,ES_MULTILINE | ES_AUTOVSCROLL | ES_AUTOHSCROLL | ES_WANTRETURN | ES_READONLY" "read-only output editor")
require_text("src/gui/win32/command_handlers.cpp" "case ID_EDIT_CLEAR_INPUT:" "Clear Input handler")
require_text("src/gui/win32/command_handlers.cpp" "case ID_EDIT_CLEAR_OUTPUT:" "Clear Output handler")
require_text("src/gui/win32/conversion_controller.cpp" "request.continue_on_error = true" "per-code GUI recovery")
require_text("src/gui/win32/conversion_controller.cpp" "result.active_ar2_seed" "live AR2 key update")
require_text("src/gui/win32/context_controls.cpp" "input_armax" "context-sensitive input Game ID")
require_text("src/gui/win32/context_controls.cpp" "output_armax" "context-sensitive output Game ID")
require_text("src/convert/conversion_service.cpp" "result.issues.push_back" "per-code issue reporting")

require_text("CMakeLists.txt" "_WIN32_WINNT=0x0601" "Windows 7 target macro")
require_text("CMakeLists.txt" "/SUBSYSTEM:WINDOWS,6.01" "Windows 7 GUI subsystem version")
require_text("CMakeLists.txt" "MSVC_TOOLSET_VERSION LESS 141" "minimum v141 Windows 7 toolset guard")
require_text("CMakeLists.txt" "MSVC_TOOLSET_VERSION GREATER 143" "maximum v143 Windows 7 toolset guard")
require_text("tools/build-windows7-x64.ps1" "Find-CompatibleVisualStudio" "multi-version Visual Studio discovery")
require_text("tools/build-windows7-x64.ps1" "ConvertFrom-VsWhereJson" "robust vswhere JSON normalization")
require_text("tools/build-windows7-x64.ps1" "ConvertFrom-Json -InputObject" "whole-document vswhere JSON parsing")
require_text("tools/build-windows7-x64.ps1" "PSObject.Properties[$Name]" "strict-mode-safe property access")
require_text("tools/build-windows7-x64.ps1" "-all -prerelease -products *" "prerelease Visual Studio discovery")
require_text("tools/build-windows7-x64.ps1" "Get-ManualVisualStudioPaths" "known-folder Visual Studio fallback")
require_text("tools/build-windows7-x64.ps1" [[VC\Tools\MSVC]] "physical MSVC toolset inspection")
forbid_text("tools/build-windows7-x64.ps1" "-requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64" "fragile workload-metadata-only filter")
require_text("tools/build-windows7-x64.ps1" "Visual Studio 16 2019" "Visual Studio 2019 generator support")
require_text("tools/build-windows7-x64.ps1" "Visual Studio 15 2017" "Visual Studio 2017 generator support")
require_text("src/gui/win32/main.cpp" "omni::cli::run_cli" "unified GUI/CLI dispatcher")
require_text("src/gui/win32/file_commands.cpp" "formats/text/copy_paste_cleaner.hpp" "text-file cleaner declaration include")
require_text("CMakeLists.txt" "/MANIFEST:EMBED" "MSVC embedded-manifest linker option")
require_text("CMakeLists.txt" "/MANIFESTINPUT:" "MSVC manifest input linker option")
require_text("CMakeLists.txt" [=[${OMNI_GENERATED_RESOURCE_DIR}/OmniConvert.manifest]=] "generated application manifest path")
require_text("src/gui/win32/resources/resource.rc" "#ifdef OMNI_EMBED_MANIFEST_RESOURCE" "non-MSVC manifest resource guard")
require_text("src/gui/win32/resources/resource.rc" "1 24 \"OmniConvert.manifest\"" "non-MSVC application manifest resource")
require_text("CMakeLists.txt" "$<$<COMPILE_LANGUAGE:RC>:OMNI_EMBED_MANIFEST_RESOURCE>" "MinGW-only manifest resource definition")
require_text("tools/build-windows7-x64.ps1" "CreateFile2" "Windows 8+ import rejection")
require_text("build-windows7-x64.cmd" [[rmdir /s /q "%~dp0build"]] "unconditional temporary build-folder cleanup")
require_text("build-windows7-x64.cmd" [[set "RESULT=%ERRORLEVEL%"]] "build result preservation before cleanup")
require_text("build-windows7-x64.cmd" [[set "FINISHED_DIR=%FINISHED_DIR%0-Finished"]] "finished-output root")
require_text("build-windows7-x64.cmd" [[Logs remain in: %FINISHED_DIR%\logs]] "log-folder preservation message")
require_text("build-windows7-x64.cmd" [[Release files remain in: %FINISHED_DIR%\dist]] "release-folder preservation message")
require_text("tools/build-windows7-x64.ps1" [[0-Finished\dist\Win7-x64]] "finished release default")
require_text("tools/build-windows7-x64.ps1" [[0-Finished\logs]] "finished log default")
require_text("tools/build-windows7-x64.ps1" "Repair-FutureProjectTimestamps" "future timestamp repair")
require_text("tools/build-windows7-x64.ps1" "CMAKE_SUPPRESS_REGENERATION=ON" "scripted-build regeneration suppression")
require_text(".github/workflows/build-windows7-x64.yml" [[0-Finished/dist/Win7-x64/Release/]] "GitHub finished release path")
require_text(".gitignore" [[0-Finished/]] "finished-output ignore rule")
require_text(".github/workflows/build-windows7-x64.yml" "actions/upload-artifact@v6" "GitHub release artifact upload")

require_text("CMakeLists.txt" "src/gui/win32/armax_disc_hash_dialog.cpp" "manual AR MAX disc-hash GUI source")
require_text("src/gui/win32/resources/resource.rc" "IDC_ARMAX_DISC_HASH_MANUAL" "manual AR MAX disc-hash button")
require_text("src/gui/win32/resources/resource.rc" "IDD_ARMAX_DISC_HASH" "manual AR MAX disc-hash dialog")
require_text("src/gui/win32/armax_disc_hash_dialog.cpp" "compute_disc_hash_from_files" "SYSTEM.CNF and ELF disc-hash calculation")
require_text("src/gui/win32/armax_disc_hash_dialog.cpp" "ArmaxDiscHash.json" "AR MAX disc-hash mapping persistence")
